services:
  nginx:
    image: nginx:latest
    container-name: nginx-proxy
    ports: 
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      fe:
      auth-service:
        condition: service_healthy
      file-service:
        condition: service_healthy
      db:
        condition: service_healthy

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./fe:/usr/src/sf-fe
      - /usr/src/sf-fe/node_modules

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile 
    expose:
      - "8081"
    env_file:
      - ./auth-service/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    expose:
      - "8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://file-service:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
